# common configurations
environment: local
http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

server:
  appVersion: 1.0.0
  mode: Development
  debug: true

mysql:
  address: 127.0.0.1:6603
  database: user-center
  username: root
  password: olah123
  protocol: tcp
  parseTime: true
redis:
  addr: 127.0.0.1:16379
  password:
  db: 0

logger:
  development: true
  level: debug
  logType: 0